var searchData=
[
  ['table_20buckets_0',['Tutorial 03 – Hash Table Buckets',['..//home/yjlee/libttak/tutorials/03-hash-table-buckets/README.md#autotoc_md65',1,'']]],
  ['targets_1',['Key Performance Targets',['..//home/yjlee/libttak/bench/ttl-cache-multithread-bench/README.md#autotoc_md8',1,'']]],
  ['testing_2',['12. Documentation &amp;amp; Testing',['../md_SPECS.html#autotoc_md57',1,'']]],
  ['the_20benchmark_3',['Running the Benchmark',['..//home/yjlee/libttak/bench/ttl-cache-multithread-bench/README.md#autotoc_md9',1,'']]],
  ['the_20bigscript_20program_4',['The BigScript Program',['..//home/yjlee/libttak/tutorials/43-bigscript/01-getting-started/README.md#autotoc_md171',1,'']]],
  ['the_20deterministic_20lru_20synchronous_20eviction_5',['The Deterministic LRU &amp;amp; Synchronous Eviction',['..//home/yjlee/libttak/tutorials/36-trace-memory/README.md#autotoc_md133',1,'']]],
  ['the_20example_6',['the Example',['..//home/yjlee/libttak/tutorials/43-bigscript/01-getting-started/README.md#autotoc_md172',1,'Running the Example'],['..//home/yjlee/libttak/tutorials/43-bigscript/02-variables-arithmetic/README.md#autotoc_md177',1,'Running the Example'],['..//home/yjlee/libttak/tutorials/43-bigscript/03-control-flow/README.md#autotoc_md181',1,'Running the Example'],['..//home/yjlee/libttak/tutorials/43-bigscript/04-builtins/README.md#autotoc_md185',1,'Running the Example'],['..//home/yjlee/libttak/tutorials/43-bigscript/05-complex-math/README.md#autotoc_md190',1,'Running the Example']]],
  ['the_20ols_20principle_7',['Mathematical Foundation: The OLS Principle',['../index.html#autotoc_md22',1,'']]],
  ['the_20sample_8',['Building the sample',['..//home/yjlee/libttak/tutorials/01-getting-started/README.md#autotoc_md61',1,'']]],
  ['this_20matters_9',['Why this matters?',['..//home/yjlee/libttak/tutorials/36-trace-memory/README.md#autotoc_md136',1,'']]],
  ['thread_20pool_20async_10',['Stage 3 – Thread Pool &amp;amp; Async',['../md_tutorials_2CLONE__PATH.html#autotoc_md198',1,'']]],
  ['thread_20pool_20core_11',['Tutorial 12 – Thread Pool Core',['..//home/yjlee/libttak/tutorials/12-thread-pool-core/README.md#autotoc_md82',1,'']]],
  ['threaded_20benchmark_12',['1. TTL Cache Multi-threaded Benchmark',['..//home/yjlee/libttak/bench/README.md#autotoc_md2',1,'']]],
  ['threaded_20ttl_20cache_20benchmark_13',['Multi-threaded TTL Cache Benchmark',['..//home/yjlee/libttak/bench/ttl-cache-multithread-bench/README.md#autotoc_md6',1,'']]],
  ['timing_20limiters_20stats_14',['Stage 4 – Timing + Limiters + Stats',['../md_tutorials_2CLONE__PATH.html#autotoc_md199',1,'']]],
  ['timing_20services_15',['Tutorial 17 – Timing Services',['..//home/yjlee/libttak/tutorials/17-timing-services/README.md#autotoc_md92',1,'']]],
  ['to_20run_16',['to Run',['..//home/yjlee/libttak/tutorials/36-trace-memory/README.md#autotoc_md134',1,'How to Run'],['..//home/yjlee/libttak/tutorials/37-shared-memory-ownership/README.md#autotoc_md139',1,'How to Run']]],
  ['to_20run_20bigscript_17',['How to Run BigScript',['..//home/yjlee/libttak/tutorials/43-bigscript/README.md#autotoc_md193',1,'']]],
  ['tools_18',['Tools',['..//home/yjlee/libttak/bench/README.md#autotoc_md5',1,'Analysis Tools'],['..//home/yjlee/libttak/tutorials/README.md#autotoc_md214',1,'Files &amp; Tools']]],
  ['tracing_20lru_20caching_19',['Lesson 36: Memory Tracing &amp;amp; LRU Caching',['..//home/yjlee/libttak/tutorials/36-trace-memory/README.md#autotoc_md131',1,'']]],
  ['tree_20',['Tree',['..//home/yjlee/libttak/tutorials/22-mem-tree/README.md#autotoc_md102',1,'Tutorial 22 – Mem Tree'],['..//home/yjlee/libttak/tutorials/30-bplus-tree/README.md#autotoc_md119',1,'Tutorial 30 – B+ Tree'],['..//home/yjlee/libttak/tutorials/31-btree/README.md#autotoc_md121',1,'Tutorial 31 – B-Tree']]],
  ['trees_20ast_21',['Stage 7 – Trees + AST',['../md_tutorials_2CLONE__PATH.html#autotoc_md202',1,'']]],
  ['true_22',['&lt;span class=&quot;tt&quot;&gt;access_ebr(..., protected=true)&lt;/span&gt;',['..//home/yjlee/libttak/tutorials/38-ebr-shared/README.md#autotoc_md146',1,'']]],
  ['ttak_5fbench_20c_23',['2. General Benchmark Hub (&lt;span class=&quot;tt&quot;&gt;ttak_bench.c&lt;/span&gt;)',['..//home/yjlee/libttak/bench/README.md#autotoc_md3',1,'']]],
  ['ttak_5fmem_5falloc_5fsafe_24',['4.1 Fortress Allocator (&lt;span class=&quot;tt&quot;&gt;ttak_mem_alloc_safe&lt;/span&gt;)',['../md_SPECS.html#autotoc_md46',1,'']]],
  ['ttak_5fshared_5fswap_5febr_25',['&lt;span class=&quot;tt&quot;&gt;ttak_shared_swap_ebr&lt;/span&gt;',['..//home/yjlee/libttak/tutorials/38-ebr-shared/README.md#autotoc_md145',1,'']]],
  ['ttl_20cache_20benchmark_26',['Multi-threaded TTL Cache Benchmark',['..//home/yjlee/libttak/bench/ttl-cache-multithread-bench/README.md#autotoc_md6',1,'']]],
  ['ttl_20cache_20benchmarks_20compiler_20sweep_27',['TTL Cache Benchmarks (Compiler Sweep)',['../index.html#autotoc_md37',1,'']]],
  ['ttl_20cache_20multi_20threaded_20benchmark_28',['1. TTL Cache Multi-threaded Benchmark',['..//home/yjlee/libttak/bench/README.md#autotoc_md2',1,'']]],
  ['tutorial_2001_20–_20getting_20started_29',['Tutorial 01 – Getting Started',['..//home/yjlee/libttak/tutorials/01-getting-started/README.md#autotoc_md59',1,'']]],
  ['tutorial_2002_20–_20helper_20workflow_30',['Tutorial 02 – Helper Workflow',['..//home/yjlee/libttak/tutorials/02-helper-workflow/README.md#autotoc_md63',1,'']]],
  ['tutorial_2003_20–_20hash_20table_20buckets_31',['Tutorial 03 – Hash Table Buckets',['..//home/yjlee/libttak/tutorials/03-hash-table-buckets/README.md#autotoc_md65',1,'']]],
  ['tutorial_2004_20–_20map_20operations_32',['Tutorial 04 – Map Operations',['..//home/yjlee/libttak/tutorials/04-map-operations/README.md#autotoc_md66',1,'']]],
  ['tutorial_2005_20–_20pool_20allocator_33',['Tutorial 05 – Pool Allocator',['..//home/yjlee/libttak/tutorials/05-pool-allocator/README.md#autotoc_md68',1,'']]],
  ['tutorial_2006_20–_20ring_20buffer_34',['Tutorial 06 – Ring Buffer',['..//home/yjlee/libttak/tutorials/06-ring-buffer/README.md#autotoc_md70',1,'']]],
  ['tutorial_2007_20–_20set_20container_35',['Tutorial 07 – Set Container',['..//home/yjlee/libttak/tutorials/07-set-container/README.md#autotoc_md72',1,'']]],
  ['tutorial_2008_20–_20logger_20basics_36',['Tutorial 08 – Logger Basics',['..//home/yjlee/libttak/tutorials/08-logger-basics/README.md#autotoc_md74',1,'']]],
  ['tutorial_2009_20–_20mutex_20primitives_37',['Tutorial 09 – Mutex Primitives',['..//home/yjlee/libttak/tutorials/09-mutex-primitives/README.md#autotoc_md76',1,'']]],
  ['tutorial_2010_20–_20spinlock_20variants_38',['Tutorial 10 – Spinlock Variants',['..//home/yjlee/libttak/tutorials/10-spinlock-variants/README.md#autotoc_md78',1,'']]],
  ['tutorial_2011_20–_20portable_20atomics_39',['Tutorial 11 – Portable Atomics',['..//home/yjlee/libttak/tutorials/11-portable-atomics/README.md#autotoc_md80',1,'']]],
  ['tutorial_2012_20–_20thread_20pool_20core_40',['Tutorial 12 – Thread Pool Core',['..//home/yjlee/libttak/tutorials/12-thread-pool-core/README.md#autotoc_md82',1,'']]],
  ['tutorial_2013_20–_20worker_20ownership_41',['Tutorial 13 – Worker Ownership',['..//home/yjlee/libttak/tutorials/13-worker-ownership/README.md#autotoc_md84',1,'']]],
  ['tutorial_2014_20–_20priority_20queues_42',['Tutorial 14 – Priority Queues',['..//home/yjlee/libttak/tutorials/14-priority-queues/README.md#autotoc_md86',1,'']]],
  ['tutorial_2015_20–_20async_20primitives_43',['Tutorial 15 – Async Primitives',['..//home/yjlee/libttak/tutorials/15-async-primitives/README.md#autotoc_md88',1,'']]],
  ['tutorial_2016_20–_20async_20scheduler_44',['Tutorial 16 – Async Scheduler',['..//home/yjlee/libttak/tutorials/16-async-scheduler/README.md#autotoc_md90',1,'']]],
  ['tutorial_2017_20–_20timing_20services_45',['Tutorial 17 – Timing Services',['..//home/yjlee/libttak/tutorials/17-timing-services/README.md#autotoc_md92',1,'']]],
  ['tutorial_2018_20–_20rate_20limiters_46',['Tutorial 18 – Rate Limiters',['..//home/yjlee/libttak/tutorials/18-rate-limiters/README.md#autotoc_md94',1,'']]],
  ['tutorial_2019_20–_20stats_20aggregator_47',['Tutorial 19 – Stats Aggregator',['..//home/yjlee/libttak/tutorials/19-stats-aggregator/README.md#autotoc_md96',1,'']]],
  ['tutorial_2020_20–_20owner_20subsystem_48',['Tutorial 20 – Owner Subsystem',['..//home/yjlee/libttak/tutorials/20-owner-subsystem/README.md#autotoc_md98',1,'']]],
  ['tutorial_2021_20–_20epoch_20gc_49',['Tutorial 21 – Epoch GC',['..//home/yjlee/libttak/tutorials/21-epoch-gc/README.md#autotoc_md100',1,'']]],
  ['tutorial_2022_20–_20mem_20tree_50',['Tutorial 22 – Mem Tree',['..//home/yjlee/libttak/tutorials/22-mem-tree/README.md#autotoc_md102',1,'']]],
  ['tutorial_2023_20–_20bigint_20foundations_51',['Tutorial 23 – Bigint Foundations',['..//home/yjlee/libttak/tutorials/23-bigint-foundations/README.md#autotoc_md104',1,'']]],
  ['tutorial_2024_20–_20bigmul_20bigreal_52',['Tutorial 24 – Bigmul + Bigreal',['..//home/yjlee/libttak/tutorials/24-bigmul-bigreal/README.md#autotoc_md106',1,'']]],
  ['tutorial_2025_20–_20sum_20of_20divisors_53',['Tutorial 25 – Sum of Divisors',['..//home/yjlee/libttak/tutorials/25-sum-divisors/README.md#autotoc_md108',1,'']]],
  ['tutorial_2026_20–_20factorization_54',['Tutorial 26 – Factorization',['..//home/yjlee/libttak/tutorials/26-factorization/README.md#autotoc_md110',1,'']]],
  ['tutorial_2027_20–_20ntt_20module_55',['Tutorial 27 – NTT Module',['..//home/yjlee/libttak/tutorials/27-ntt-module/README.md#autotoc_md113',1,'']]],
  ['tutorial_2028_20–_20sha_20256_56',['Tutorial 28 – SHA-256',['..//home/yjlee/libttak/tutorials/28-sha256/README.md#autotoc_md115',1,'']]],
  ['tutorial_2029_20–_20ast_20walking_57',['Tutorial 29 – AST Walking',['..//home/yjlee/libttak/tutorials/29-ast-walking/README.md#autotoc_md117',1,'']]],
  ['tutorial_2030_20–_20b_20tree_58',['Tutorial 30 – B+ Tree',['..//home/yjlee/libttak/tutorials/30-bplus-tree/README.md#autotoc_md119',1,'']]],
  ['tutorial_2031_20–_20b_20tree_59',['Tutorial 31 – B-Tree',['..//home/yjlee/libttak/tutorials/31-btree/README.md#autotoc_md121',1,'']]],
  ['tutorial_2032_20–_20aliquot_20integration_60',['Tutorial 32 – Aliquot Integration',['..//home/yjlee/libttak/tutorials/32-aliquot-integration/README.md#autotoc_md123',1,'']]],
  ['tutorial_2033_20–_20bench_20suite_61',['Tutorial 33 – Bench Suite',['..//home/yjlee/libttak/tutorials/33-bench-suite/README.md#autotoc_md125',1,'']]],
  ['tutorial_2034_20–_20dangerous_20primer_62',['Tutorial 34 – Dangerous Primer',['..//home/yjlee/libttak/tutorials/34-dangerous-primer/README.md#autotoc_md127',1,'']]],
  ['tutorial_2035_20–_20context_20bridge_63',['Tutorial 35 – Context Bridge',['..//home/yjlee/libttak/tutorials/35-context-bridge/README.md#autotoc_md129',1,'']]],
  ['tutorial_2038_3a_20epoch_20based_20reclamation_20ebr_20for_20shared_20objects_64',['Tutorial 38: Epoch-based Reclamation (EBR) for Shared Objects',['..//home/yjlee/libttak/tutorials/38-ebr-shared/README.md#autotoc_md142',1,'']]],
  ['tutorial_20outline_65',['Tutorial Outline',['..//home/yjlee/libttak/tutorials/DANGEROUS/README.md#autotoc_md210',1,'']]],
  ['tutorials_66',['Tutorials',['..//home/yjlee/libttak/tutorials/DANGEROUS/README.md#autotoc_md207',1,'DANGEROUS Tutorials'],['..//home/yjlee/libttak/tutorials/README.md#autotoc_md211',1,'LibTTAK Tutorials']]],
  ['type_20conversion_20and_20construction_67',['Type Conversion and Construction',['..//home/yjlee/libttak/tutorials/43-bigscript/05-complex-math/README.md#autotoc_md187',1,'']]]
];
