var searchData=
[
  ['access_5febr_20protected_20false_0',['&lt;span class=&quot;tt&quot;&gt;access_ebr(..., protected=false)&lt;/span&gt;',['..//home/yjlee/libttak/tutorials/38-ebr-shared/README.md#autotoc_md147',1,'']]],
  ['access_5febr_20protected_20true_1',['&lt;span class=&quot;tt&quot;&gt;access_ebr(..., protected=true)&lt;/span&gt;',['..//home/yjlee/libttak/tutorials/38-ebr-shared/README.md#autotoc_md146',1,'']]],
  ['adding_20new_20blueprints_2',['Adding New Blueprints',['..//home/yjlee/libttak/blueprints/README.md#autotoc_md15',1,'']]],
  ['aggregator_3',['Tutorial 19 – Stats Aggregator',['..//home/yjlee/libttak/tutorials/19-stats-aggregator/README.md#autotoc_md96',1,'']]],
  ['ai_20assisted_20development_4',['Practical Utility for AI-Assisted Development',['../index.html#autotoc_md27',1,'']]],
  ['aliquot_20integration_5',['Tutorial 32 – Aliquot Integration',['..//home/yjlee/libttak/tutorials/32-aliquot-integration/README.md#autotoc_md123',1,'']]],
  ['allocator_6',['Tutorial 05 – Pool Allocator',['..//home/yjlee/libttak/tutorials/05-pool-allocator/README.md#autotoc_md68',1,'']]],
  ['allocator_20ttak_5fmem_5falloc_5fsafe_7',['4.1 Fortress Allocator (&lt;span class=&quot;tt&quot;&gt;ttak_mem_alloc_safe&lt;/span&gt;)',['../md_SPECS.html#autotoc_md46',1,'']]],
  ['analysis_20tools_8',['Analysis Tools',['..//home/yjlee/libttak/bench/README.md#autotoc_md5',1,'']]],
  ['and_20arithmetic_9',['02 - Variables and Arithmetic',['..//home/yjlee/libttak/tutorials/43-bigscript/02-variables-arithmetic/README.md#autotoc_md174',1,'']]],
  ['and_20c_10',['Comparison: LibTTAK, Rust, and C++',['../index.html#autotoc_md31',1,'']]],
  ['and_20complex_20numbers_11',['05 - Real and Complex Numbers',['..//home/yjlee/libttak/tutorials/43-bigscript/05-complex-math/README.md#autotoc_md186',1,'']]],
  ['and_20construction_12',['Type Conversion and Construction',['..//home/yjlee/libttak/tutorials/43-bigscript/05-complex-math/README.md#autotoc_md187',1,'']]],
  ['and_20epochgc_20integration_13',['EBR and EpochGC Integration',['..//home/yjlee/libttak/tutorials/38-ebr-shared/README.md#autotoc_md149',1,'']]],
  ['and_20running_14',['Building and Running',['..//home/yjlee/libttak/tutorials/38-ebr-shared/README.md#autotoc_md150',1,'']]],
  ['and_20sn_15',['Input Arguments: &lt;span class=&quot;tt&quot;&gt;seed&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;sn&lt;/span&gt;',['..//home/yjlee/libttak/tutorials/43-bigscript/04-builtins/README.md#autotoc_md184',1,'']]],
  ['application_20layer_16',['Stage 8 – Application Layer',['../md_tutorials_2CLONE__PATH.html#autotoc_md203',1,'']]],
  ['architectural_20map_17',['Integrated Architectural Map',['../index.html#autotoc_md24',1,'']]],
  ['architectural_20overview_18',['3. Architectural Overview',['../md_SPECS.html#autotoc_md44',1,'']]],
  ['architectural_20philosophy_19',['Architectural Philosophy',['..//home/yjlee/libttak/bench/README.md#autotoc_md4',1,'']]],
  ['arena_20families_20signal_20guards_20',['Stage 10 – Arena Families &amp;amp; Signal Guards',['../md_tutorials_2CLONE__PATH.html#autotoc_md205',1,'']]],
  ['arena_20memory_20orchestration_21',['Lesson 40: Arena Memory Orchestration',['..//home/yjlee/libttak/tutorials/40-arena-memory/README.md#autotoc_md157',1,'']]],
  ['arenas_22',['4.3 Detachable Arenas',['../md_SPECS.html#autotoc_md48',1,'']]],
  ['arguments_3a_20seed_20and_20sn_23',['Input Arguments: &lt;span class=&quot;tt&quot;&gt;seed&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;sn&lt;/span&gt;',['..//home/yjlee/libttak/tutorials/43-bigscript/04-builtins/README.md#autotoc_md184',1,'']]],
  ['arithmetic_24',['02 - Variables and Arithmetic',['..//home/yjlee/libttak/tutorials/43-bigscript/02-variables-arithmetic/README.md#autotoc_md174',1,'']]],
  ['arithmetic_20operators_25',['Arithmetic Operators',['..//home/yjlee/libttak/tutorials/43-bigscript/02-variables-arithmetic/README.md#autotoc_md176',1,'']]],
  ['as_20data_26',['Deterministic Lifetime-as-Data',['../index.html#autotoc_md28',1,'']]],
  ['assisted_20development_27',['Practical Utility for AI-Assisted Development',['../index.html#autotoc_md27',1,'']]],
  ['ast_28',['Stage 7 – Trees + AST',['../md_tutorials_2CLONE__PATH.html#autotoc_md202',1,'']]],
  ['ast_20walking_29',['Tutorial 29 – AST Walking',['..//home/yjlee/libttak/tutorials/29-ast-walking/README.md#autotoc_md117',1,'']]],
  ['async_30',['Stage 3 – Thread Pool &amp;amp; Async',['../md_tutorials_2CLONE__PATH.html#autotoc_md198',1,'']]],
  ['async_20primitives_31',['Tutorial 15 – Async Primitives',['..//home/yjlee/libttak/tutorials/15-async-primitives/README.md#autotoc_md88',1,'']]],
  ['async_20scheduler_32',['Tutorial 16 – Async Scheduler',['..//home/yjlee/libttak/tutorials/16-async-scheduler/README.md#autotoc_md90',1,'']]],
  ['atomics_33',['Tutorial 11 – Portable Atomics',['..//home/yjlee/libttak/tutorials/11-portable-atomics/README.md#autotoc_md80',1,'']]]
];
